
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    # 学生端
    server {
        client_max_body_size 10m;
        listen 6001;
        server_name  ueit-user-web;

        # 对应 Dockerfile 中 /usr/share/nginx/html/ueit-user-web
        root         /usr/share/nginx/html/ueit-user-web;
        index        index.html;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # 这里仍然反向代理到 16000，按需修改为后端服务地址
        location /api/ {
           proxy_pass  http://host.docker.internal:16000;
           proxy_set_header   X-Real-IP $remote_addr;
           proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /ueupload {
            alias /usr/share/nginx/html/resource/web-file;
        }
    }

    # 管理端
    server {
        client_max_body_size 1024m;
        listen 6003;
        server_name  ueit-admin;

        # 对应 Dockerfile 中 /usr/share/nginx/html/ueit-admin
        root         /usr/share/nginx/html/ueit-admin;
        index        index.html;

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # 这里仍然反向代理到 16002，按需修改为后端服务地址
        location /api/ {
           proxy_pass  http://host.docker.internal:16002;
           proxy_read_timeout 300;
           proxy_set_header   X-Real-IP $remote_addr;
           proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header   X-Forwarded-Proto $scheme;
        }

        location /ueupload {
            alias /usr/share/nginx/html/resource/web-file;
        }
    }

    # 默认站点（可选）
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

}
