name: Build Docker & Release

on:
  push:
    branches:
      - main
      - Docker-Dev

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 4. 构建所有 Dockerfile
    - name: Build and push Docker images
      run: |
        # 定义包含 Dockerfile 的文件夹
        folders=("WebBE" "WebFE/wdd-admin" "WebFE/wdd-user-web") # 修改为你的文件夹名称
        for folder in "${folders[@]}"; do
          image="${folder}"
          echo "Building $image from $folder/Dockerfile..."
          docker build -t ${image}:${GITHUB_SHA} ./${folder}
          docker tag ${image}:${GITHUB_SHA} ${image}:latest
          docker push ${image}:${GITHUB_SHA}
          docker push ${image}:latest
        done